config/routes.rb
Pandorando::Application.routes.draw do
  

   get "home/index"
   
   get "homePage/index"

   resources :gifts
 

   resources :categories

   resources :answers

   resources :questions

   
   root :to => "homePage#index"
 
   resources :users

   resources :resposta
 
   match ':controller(/:action(/:id))'

end

app/models/gift.rb
class Gift
  include Mongoid::Document
  field :name, :type => String
  field :price, :type => String
  field :rating, :type => Integer, :default => 0
  
  has_and_belongs_to_many :perfils
  
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  # GET /gifts
  # GET /gifts.xml
  def index
    
    if session[:autorizado] == true
      # @gifts = (Gift.limit((Constants::PAGINA).to_i)).asc(:name)
      @gifts = Gift.asc(:name)
      @gift = Gift.new
      @index = "presentes"
      @perfis = Perfil.all

      respond_to do |format|
        format.html # index.html.erb
        format.js
      end
    else
      
      respond_to do |format|
        format.html { redirect_to(:controller => "home", :action => "admin") }
      end
      
    end
    
  end

  # GET /gifts/1
  # GET /gifts/1.xml
  def show
    @gift = Gift.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.js
    end
  end

  # GET /gifts/new
  # GET /gifts/new.xml
  def new
    @gift = Gift.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  # GET /gifts/1/edit
  def edit
    @gift = Gift.find(params[:id])
  end

  # POST /gifts
  # POST /gifts.xml
  def create
    
    @gift = Gift.new(params[:gift])

    respond_to do |format|
      if @gift.save
        format.html { redirect_to(@gift, :notice => 'Gift was successfully created.') }
        format.js
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /gifts/1
  # PUT /gifts/1.xml
  def update
    @gift = Gift.find(params[:id])

    respond_to do |format|
      if @gift.update_attributes(params[:gift])
        format.html { redirect_to(@gift, :notice => 'Gift was successfully updated.') }
        format.js
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.xml
  def destroy
    @gift = Gift.find(params[:id])
    @gift.destroy

    respond_to do |format|
      format.html { redirect_to(gifts_url) }
      format.js
    end
  end
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/views/gifts/_form.html.erb
<%= form_for(@gift, :remote => true) do |f| %>
  <% if @gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gift.errors.count, "error") %> prohibited this gift from being saved:</h2>

      <ul>
      <% @gift.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p class="form_field">
    <label class="label"><%= f.label :name %></label>
    <label class="text_field"><%= f.text_field :name %></label>
  </p>
  <div class="buttons">
    <a><%= f.submit %></a>
  </div>
<% end %>

app/views/gifts/_gift.html.erb
<tr id="<%= dom_id gift %>" class="show_grid">
	<td style="width:30%"><%= gift.name %></td>
	<% for perfil in gift.perfils %>
		<td style="width:10%"><%= perfil.title %></td>
	<% end %>
    <td><%= link_to 'Show', gift, :remote => true %></td>
    <td><%= link_to 'Edit', edit_gift_path(gift), :remote => true %></td>
    <td><%= link_to 'Destroy', gift, :confirm => 'Are you sure?', :method => :delete, :remote => true %></td>
</tr>

app/views/gifts/create.js.erb
$('<%= escape_javascript(render(:partial => @gift))%>').appendTo('#gifts');
$("#new_gift")[0].reset();

app/views/gifts/destroy.js.erb
$('#<%= dom_id @gift %>').remove();

app/views/gifts/edit.html.erb
<h1>Editing gift</h1>

<%= render 'form' %>

<%= link_to 'Show', @gift %> |
<%= link_to 'Back', gifts_path %>

app/views/gifts/edit.js.erb
$("#form > form").replaceWith("<%= escape_javascript(render(:partial => "form"))%>")

app/views/gifts/index.html.erb
<div class="h_text">
	<!-- <img alt="" src="images/1-t1.jpg" />--><h1>Presentes</h1><br />
</div>
<div class="padding">
	<div class="main_content">
		<div class="show">
			<table id="gifts" class="grid">
				<thead>
					<tr>
						<th>Nome</th>
						<th>Show</th>
						<th>Edit</th>
						<th>Remove</th>
					</tr>
				</thead>
				<tbody>
					<% @gifts.each do |gift| %>
						<%= render gift %>
					<% end %>
				</tbody>
				<tfooter>

				</tfooter>
			</table>
		</div>
		<div class="form">
			<h2>New Answer</h2>
			<div id="form"><%= render :partial => "form" %></div>
		</div>
	</div>
</div>

app/views/gifts/new.html.erb
<h1>New gift</h1>

<%= render 'form' %>

<%= link_to 'Back', gifts_path %>

app/views/gifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @gift.name %>
</p>


<%= link_to 'Edit', edit_gift_path(@gift) %> |
<%= link_to 'Back', gifts_path %>

app/views/gifts/update.js.erb
$("#<%= dom_id(@gift) %>").replaceWith("<%= escape_javascript(render(:partial => @gift)) %>");
<% @gift = Gift.new # reset for new form %>
$(".edit_gift").replaceWith("<%= escape_javascript(render(:partial => "form"))%>")
$(".new_gift")[0].reset();