config/routes.rb
Pandorando::Application.routes.draw do
  

   get "home/index"
   
   get "homePage/index"

   resources :gifts
 

   resources :categories

   resources :answers

   resources :questions

   
   root :to => "homePage#index"
 
   resources :users

   resources :resposta
 
   match ':controller(/:action(/:id))'

end

app/models/answer.rb
class Answer
  include Mongoid::Document
  field :enunciation, :type => String
  
  belongs_to :question
  has_many :AnswerCharacteristicWeight, :dependent => :destroy
  
  validates :enunciation, :presence => true
end

app/models/characteristic.rb
class Characteristic
  
  attr_accessor :name
  attr_accessor :id
  attr_accessor :referencias

  def initialize(id, nome, referencias)
    @name = nome
    @id = id
    @referencias = referencias
  end
  
  def Characteristic.get_characteristics
    array = Array.new
    array.push(Characteristic.new(0,'Sexo', 1))
    array.push(Characteristic.new(1,'Innovator', 3)) 
    array.push(Characteristic.new(2,'Thinker', 2)) 
    array.push(Characteristic.new(3,'Achiever', 2)) 
    array.push(Characteristic.new(4,'Experiencer', 2))
    array.push(Characteristic.new(5,'Beliver', 2)) 
    array.push(Characteristic.new(6,'Striever', 2)) 
    array.push(Characteristic.new(7,'Maker', 2)) 
    array.push(Characteristic.new(8,'Survivor', 11))
    return array
  end
  
  def Characteristic.get_characteristic_by_name(searching_characteristic_name)
    characteristics_array = Characteristic.get_characteristics
    characteristics_array.each { |characteristic|
      if characteristic.name.casecmp(searching_characteristic_name)  == 0 then
        puts characteristic.name
        return characteristic
      end
    }
    
    puts '=============== ERRO ================'
    puts "Chamada do metodo Characteristic.get_characteristic_by_name - ERRO - Caracteristica nao encontrada"
    puts '=============== ERRO ================'
    
    return nil
  end
  
  def Characteristic.get_characteristic_by_id(searching_characteristic_id)
    characteristics_array = Characteristic.get_characteristics
    characteristics_array.each { |characteristic|
      if characteristic.id == searching_characteristic_id then
        return characteristic
      end
    }
    
    puts '=============== ERRO ================'
    puts "Chamada do metodo Characteristic.get_characteristic_by_id - ERRO - Caracteristica nao encontrada"
    puts '=============== ERRO ================'
    
    return nil
  end
  
  def == (other_characteristic)
     @id == other_characteristic.id
  end
  
end

app/models/constants.rb
class Constants
  
  # Constants to calculate the soa algorithm
  NEURONS_HEIGHT = 30
  NEURONS_WIDTH = 30
  
  NEIGHBOURHOOD_RADIUS = (NEURONS_HEIGHT / 7).to_f #Deve ser aproximadamente 3
  LEARNING_RATE = 0.5
  INTERATIONS = 30
  
  
  # Domain of the input and weights values
  DOMAIN = [[0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0]]
  
  TRAIN_MODE = false
  
  CHAR_NUMBER = 0
  
  SENHA_PANDORANDO = "oyama"
  
  PAGINA = 15
  
end

app/models/gift.rb
class Gift
  include Mongoid::Document
  field :name, :type => String
  field :price, :type => String
  field :rating, :type => Integer, :default => 0
  
  has_and_belongs_to_many :perfils
  
end

app/models/history.rb
class History
  include Mongoid::Document
  field :weight0, :type => Float
  field :weight1, :type => Float
  field :weight2, :type => Float
  field :weight3, :type => Float
  field :weight4, :type => Float
  field :weight5, :type => Float
  field :weight6, :type => Float
  field :weight7, :type => Float
  field :weight8, :type => Float
  field :user_mail, :type => String
end

app/models/network.rb
class Network
  include Mongoid::Document
  field :positionx, :type => Integer
  field :positiony, :type => Integer
  field :weight0, :type => Float
  field :weight1, :type => Float
  field :weight2, :type => Float
  field :weight3, :type => Float
  field :weight4, :type => Float
  field :weight5, :type => Float
  field :weight6, :type => Float
  field :weight7, :type => Float
  field :weight8, :type => Float
  field :match_count, :type => Integer, :default => 0
end

app/models/perfil.rb
class Perfil
  include Mongoid::Document
  field :title, :type => String
  field :positionx, :type => Integer
  field :positiony, :type => Integer
  field :match_count, :type => Integer, :default => 1
  field :radius, :type => Float
  has_and_belongs_to_many :gifts
  
end

app/models/produto.rb
class Produto
  include Mongoid::Document
  field :field1, :type => String
  field :field2, :type => String
  field :fields, :type => Integer
  
end

app/models/question.rb
class Question
  include Mongoid::Document
  field :enunciation, :type => String
  
  has_many :answers, :dependent => :destroy
  
  validates :enunciation, :presence => true
end

app/models/respostum.rb
class Respostum
  include Mongoid::Document
  
  attr_accessible :enuciado
  validates_presence_of :enuciado
  
end

app/models/user.rb
class User
  include Mongoid::Document
  field :name, :type => String
  field :email, :type => String
  
  # validates_presence_of :name, :email
  
end

app/controllers/question_manager_controller.rb
class QuestionManagerController < ApplicationController

  def index
    
    if session[:autorizado] == true
      @questions = Question.all
      @question = Question.new
      @index = "question_manager"

      respond_to do |format|
        format.html # index.html.erb
        format.js
      end
    else
      
        respond_to do |format|
          format.html { redirect_to(:controller => "home", :action => "admin") }
        end
      
    end
    
  end
  
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/resposta_helper.rb
module RespostaHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/helpers/som_helper.rb
module SomHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/question_manager/_answer.html.erb
<tr id="<%= dom_id resposta %>" >
	<td>
		<%= resposta.enunciation %>
		 - 
		<%= link_to 'Editar', edit_answer_path(resposta), :remote => true %>
		 - 
	    <%= link_to 'Remover', resposta, :confirm => 'Deseja realmente excluir a resposta? Todos os pesos serao perdidos.', :method => :delete, :remote => true %>
	</td>
	<%  
		caracteristicas = Characteristic.get_characteristics
		for indice_da_coluna_da_caracteristicas in 0...caracteristicas.length
			peso_da_caracteristica = 0.0;	
			caracteristica_da_coluna = caracteristicas[indice_da_coluna_da_caracteristicas];
			for peso_da_caracteristica_da_resposta in resposta.AnswerCharacteristicWeight 
				if (peso_da_caracteristica_da_resposta.characteristic_id == caracteristica_da_coluna.id)
					peso_da_caracteristica = peso_da_caracteristica_da_resposta.weight		
				end		
			end 		
	%>
		<td><input value='<%= peso_da_caracteristica %>' size='5' onchange="atualizarValorDoPeso('<%= resposta.id %>', '<%= caracteristica_da_coluna.id %>', this.value);"/></td>
	<% end %>
</tr>

app/views/question_manager/_form.html.erb
<%= form_for(@question, :remote => true) do |f| %>

<p class="info grid_6">
Adicionar pergunta
</p>

<p class="form_field">
  <label class="label"><%= f.label :enunciado %></label>
</p>
<p class="form_field">
	 <%= f.text_area :enunciation %>
	<%= f.submit "Salvar" %>
</p>

<% end %>

app/views/question_manager/_question.html.erb
<div id="<%= dom_id question %>" class="show_grid">
    <p class='enunciado-questao'>
	<span><%= question.enunciation %></span>
    - 
	<%= link_to 'Adicionar resposta', {:controller => "questions", :action => "addAnswer", :id => question}, :remote => true %>
	 - 
	<%= link_to 'Editar', edit_question_path(question), :remote => true %>
	 - 
	<%= link_to 'Remover', question, :confirm => 'Tem certeza que deseja remover a pergunta? Todas as repostas e pesos perdidos.', :method => :delete, :remote => true %>
	
</p>
<table style="width:100%">
	<thead>
		<tr>
			<td >
				Resposta/Caracteristica
			</td>
			<%  caracteristicas = Characteristic.get_characteristics
				for indice_da_coluna_da_caracteristicas in 0...caracteristicas.length				
			%>
				<td><%= caracteristicas[indice_da_coluna_da_caracteristicas].name; %></td>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<% if ((question.answers).length == 0) %>
		<tr class='sem-resposta-cadastrada'>
			<td colspan = "<%= caracteristicas.length + 1 %>">
				Nao ha respostas cadastradas
			</td>
		</tr>
		<% end %>
		<% question.answers.each do |resposta| %>
			<%= render :partial => "question_manager/answer", :locals => {:resposta => resposta} %>
		<% end %>
	</tbody>
</table>
</div>

app/views/question_manager/index.html.erb
<script type='text/javascript'>

function atualizarValorDoPeso(idDaResposta, idDaCaracteristica, pesoAtribuidoACaracteristica) {
	if (isNaN(pesoAtribuidoACaracteristica)) {
		alert('O peso deve ser numerico.');
		return;
	}
	
	$.get("/answers/addChar/" + idDaResposta, { characteristic : encodeURIComponent(idDaCaracteristica), weight: encodeURIComponent(pesoAtribuidoACaracteristica), authenticity_token : encodeURIComponent(AUTH_TOKEN) });
}
</script>
<div class="h_text">
	<!-- <img alt="" src="images/1-t1.jpg" />--><h1>Perguntas</h1><br />
</div>
<div class="padding">
	<div class="main_content">
		<div class="form">
			<div id="formulario-questao"> <%= render :partial => "form" %> </div>
		</div>
		<div class="show" id="questions">
			<% @questions.each do |question| %>
			 		<%= render :partial => "question", :locals => {:question => question} %>
			<% end %>
		</div>
	</div>
</div>