config/routes.rb
Pandorando::Application.routes.draw do
  

   get "home/index"
   
   get "homePage/index"

   resources :gifts
 

   resources :categories

   resources :answers

   resources :questions

   
   root :to => "homePage#index"
 
   resources :users

   resources :resposta
 
   match ':controller(/:action(/:id))'

end

app/models/answer.rb
class Answer
  include Mongoid::Document
  field :enunciation, :type => String
  
  belongs_to :question
  has_many :AnswerCharacteristicWeight, :dependent => :destroy
  
  validates :enunciation, :presence => true
end

app/models/characteristic.rb
class Characteristic
  
  attr_accessor :name
  attr_accessor :id
  attr_accessor :referencias

  def initialize(id, nome, referencias)
    @name = nome
    @id = id
    @referencias = referencias
  end
  
  def Characteristic.get_characteristics
    array = Array.new
    array.push(Characteristic.new(0,'Sexo', 1))
    array.push(Characteristic.new(1,'Innovator', 3)) 
    array.push(Characteristic.new(2,'Thinker', 2)) 
    array.push(Characteristic.new(3,'Achiever', 2)) 
    array.push(Characteristic.new(4,'Experiencer', 2))
    array.push(Characteristic.new(5,'Beliver', 2)) 
    array.push(Characteristic.new(6,'Striever', 2)) 
    array.push(Characteristic.new(7,'Maker', 2)) 
    array.push(Characteristic.new(8,'Survivor', 11))
    return array
  end
  
  def Characteristic.get_characteristic_by_name(searching_characteristic_name)
    characteristics_array = Characteristic.get_characteristics
    characteristics_array.each { |characteristic|
      if characteristic.name.casecmp(searching_characteristic_name)  == 0 then
        puts characteristic.name
        return characteristic
      end
    }
    
    puts '=============== ERRO ================'
    puts "Chamada do metodo Characteristic.get_characteristic_by_name - ERRO - Caracteristica nao encontrada"
    puts '=============== ERRO ================'
    
    return nil
  end
  
  def Characteristic.get_characteristic_by_id(searching_characteristic_id)
    characteristics_array = Characteristic.get_characteristics
    characteristics_array.each { |characteristic|
      if characteristic.id == searching_characteristic_id then
        return characteristic
      end
    }
    
    puts '=============== ERRO ================'
    puts "Chamada do metodo Characteristic.get_characteristic_by_id - ERRO - Caracteristica nao encontrada"
    puts '=============== ERRO ================'
    
    return nil
  end
  
  def == (other_characteristic)
     @id == other_characteristic.id
  end
  
end

app/models/constants.rb
class Constants
  
  # Constants to calculate the soa algorithm
  NEURONS_HEIGHT = 30
  NEURONS_WIDTH = 30
  
  NEIGHBOURHOOD_RADIUS = (NEURONS_HEIGHT / 7).to_f #Deve ser aproximadamente 3
  LEARNING_RATE = 0.5
  INTERATIONS = 30
  
  
  # Domain of the input and weights values
  DOMAIN = [[0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0], [0.0, 1.0]]
  
  TRAIN_MODE = false
  
  CHAR_NUMBER = 0
  
  SENHA_PANDORANDO = "oyama"
  
  PAGINA = 15
  
end

app/models/gift.rb
class Gift
  include Mongoid::Document
  field :name, :type => String
  field :price, :type => String
  field :rating, :type => Integer, :default => 0
  
  has_and_belongs_to_many :perfils
  
end

app/models/history.rb
class History
  include Mongoid::Document
  field :weight0, :type => Float
  field :weight1, :type => Float
  field :weight2, :type => Float
  field :weight3, :type => Float
  field :weight4, :type => Float
  field :weight5, :type => Float
  field :weight6, :type => Float
  field :weight7, :type => Float
  field :weight8, :type => Float
  field :user_mail, :type => String
end

app/models/network.rb
class Network
  include Mongoid::Document
  field :positionx, :type => Integer
  field :positiony, :type => Integer
  field :weight0, :type => Float
  field :weight1, :type => Float
  field :weight2, :type => Float
  field :weight3, :type => Float
  field :weight4, :type => Float
  field :weight5, :type => Float
  field :weight6, :type => Float
  field :weight7, :type => Float
  field :weight8, :type => Float
  field :match_count, :type => Integer, :default => 0
end

app/models/perfil.rb
class Perfil
  include Mongoid::Document
  field :title, :type => String
  field :positionx, :type => Integer
  field :positiony, :type => Integer
  field :match_count, :type => Integer, :default => 1
  field :radius, :type => Float
  has_and_belongs_to_many :gifts
  
end

app/models/produto.rb
class Produto
  include Mongoid::Document
  field :field1, :type => String
  field :field2, :type => String
  field :fields, :type => Integer
  
end

app/models/question.rb
class Question
  include Mongoid::Document
  field :enunciation, :type => String
  
  has_many :answers, :dependent => :destroy
  
  validates :enunciation, :presence => true
end

app/models/respostum.rb
class Respostum
  include Mongoid::Document
  
  attr_accessible :enuciado
  validates_presence_of :enuciado
  
end

app/models/user.rb
class User
  include Mongoid::Document
  field :name, :type => String
  field :email, :type => String
  
  # validates_presence_of :name, :email
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.all
    @category = Category.new
    @index = "categories"

    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.js
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.js
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.js
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.js
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/resposta_helper.rb
module RespostaHelper
end

app/helpers/result_helper.rb
module ResultHelper
end

app/helpers/som_helper.rb
module SomHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<tr id="<%= dom_id category %>" class="show_grid">
    <td style="width:70%"><%= category.name %></td>
    <td><%= link_to 'Show', category, :remote => true %></td>
    <td><%= link_to 'Edit', edit_category_path(category), :remote => true %></td>
    <td><%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete, :remote => true %></td>
</tr>

app/views/categories/_form.html.erb
<%= form_for(@category, :remote => true) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p class="form_field">
    <label class="label"><%= f.label :name %></label>
    <label class="text_field"><%= f.text_field :name %></label>
  </p>
  <div class="buttons">
    <a><%= f.submit "Save" %></a>
  </div>
<% end %>

app/views/categories/create.js.erb
$('<%= escape_javascript(render(:partial => @category))%>').appendTo('#categories');
$("#new_category")[0].reset();

app/views/categories/destroy.js.erb
$('#<%= dom_id @category %>').remove();

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="h_text">
	<!-- <img alt="" src="images/1-t1.jpg" />--><h1>Categories</h1><br />
</div>
<div class="padding">
	<div class="main_content">
		<div class="show">
			<table id="categories" class="grid">
				<thead>
					<tr>
						<th>Enunciation</th>
						<th>Show</th>
						<th>Edit</th>
						<th>Remove</th>
					</tr>
				</thead>
				<tbody>
					<% @categories.each do |category| %>
						<%= render category %>
					<% end %>
				</tbody>
				<tfooter>

				</tfooter>
			</table>
		</div>
		<div class="form">
			<h2>New Category</h2>
			<div id="form"><%= render :partial => "form" %></div>
		</div>
	</div>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/categories/update.js.erb
$("#<%= dom_id(@category) %>").replaceWith("<%= escape_javascript(render(:partial => @category)) %>");
<% @category = Category.new # reset for new form %>
$(".edit_category").replaceWith("<%= escape_javascript(render(:partial => "form"))%>")
$(".new_category")[0].reset();